import { columns } from "@/app/movies/columns";
import { DataTable } from "@/app/movies/data-table";
import { Movie } from "@/types/Movie";

export const metadata = {
  title: "All movies",
  description: "Movie management",
};

async function getMovies(): Promise<Movie[]> {
  return [
    {
      id: "movie001",
      title: "The Lost Kingdom",
      description:
        "An epic adventure of a prince seeking to reclaim his lost throne in a mystical realm.",
      duration: 142,
      releaseDate: new Date("2025-06-21"),
      rating: 8.6,
      thumbnail: "https://cdn.example.com/thumbnails/the-lost-kingdom.jpg",
      thumbnailPublicId: "movies/the-lost-kingdom-thumbnail",
      trailerUrl: "https://cdn.example.com/trailers/the-lost-kingdom.mp4",
      trailerPublicId: "trailers/the-lost-kingdom-trailer",
      genres: [
        {
          id: "genre001",
          name: "Fantasy",
          description: "Magical worlds, mythical creatures, and epic quests.",
          isActive: true,
          createdAt: new Date("2024-01-10"),
          updatedAt: new Date("2024-11-30"),
          movies: [],
        },
        {
          id: "genre002",
          name: "Adventure",
          description: "Exciting journeys and explorations across vast lands.",
          isActive: true,
          createdAt: new Date("2023-10-05"),
          updatedAt: new Date("2025-01-15"),
          movies: [],
        },
      ],
      isActive: true,
      createdAt: new Date("2025-05-01T10:00:00Z"),
      updatedAt: new Date("2025-09-01T14:30:00Z"),
    },
    {
      id: "movie002",
      title: "Silent Echoes",
      description:
        "A haunting tale of a woman who hears whispers from the past in her new home.",
      duration: 98,
      releaseDate: new Date("2024-10-15"),
      rating: 7.4,
      thumbnail: "https://cdn.example.com/thumbnails/silent-echoes.jpg",
      thumbnailPublicId: "movies/silent-echoes-thumbnail",
      trailerUrl: "https://cdn.example.com/trailers/silent-echoes.mp4",
      trailerPublicId: "trailers/silent-echoes-trailer",
      genres: [
        {
          id: "genre003",
          name: "Horror",
          description: "Movies that scare, haunt, or disturb.",
          isActive: true,
          createdAt: new Date("2022-08-20"),
          updatedAt: new Date("2024-10-01"),
          movies: [],
        },
        {
          id: "genre004",
          name: "Mystery",
          description: "Films with puzzles, clues, and dramatic twists.",
          isActive: true,
          createdAt: new Date("2023-06-15"),
          updatedAt: new Date("2024-05-12"),
          movies: [],
        },
      ],
      isActive: true,
      createdAt: new Date("2024-09-10T12:00:00Z"),
      updatedAt: new Date("2025-01-25T11:00:00Z"),
    },
    {
      id: "movie003",
      title: "Code Breaker",
      description:
        "A brilliant young hacker is recruited by a secret agency to stop cyberattacks worldwide.",
      duration: 120,
      releaseDate: new Date("2025-01-10"),
      rating: 8.1,
      thumbnail: "https://cdn.example.com/thumbnails/code-breaker.jpg",
      thumbnailPublicId: "movies/code-breaker-thumbnail",
      trailerUrl: "https://cdn.example.com/trailers/code-breaker.mp4",
      trailerPublicId: "trailers/code-breaker-trailer",
      genres: [
        {
          id: "genre005",
          name: "Action",
          description:
            "High-octane movies filled with fights, chases, and explosions.",
          isActive: true,
          createdAt: new Date("2023-01-01"),
          updatedAt: new Date("2024-06-30"),
          movies: [],
        },
        {
          id: "genre006",
          name: "Thriller",
          description: "Edge-of-your-seat movies with intense plots.",
          isActive: true,
          createdAt: new Date("2022-09-15"),
          updatedAt: new Date("2023-12-10"),
          movies: [],
        },
      ],
      isActive: true,
      createdAt: new Date("2024-11-01T08:00:00Z"),
      updatedAt: new Date("2025-01-05T15:45:00Z"),
    },
    {
      id: "movie004",
      title: "Stellar Voyage",
      description:
        "A deep-space crew encounters a wormhole that leads to the origins of the universe.",
      duration: 153,
      releaseDate: new Date("2025-08-02"),
      rating: 9.0,
      thumbnail: "https://cdn.example.com/thumbnails/stellar-voyage.jpg",
      thumbnailPublicId: "movies/stellar-voyage-thumbnail",
      trailerUrl: "https://cdn.example.com/trailers/stellar-voyage.mp4",
      trailerPublicId: "trailers/stellar-voyage-trailer",
      genres: [
        {
          id: "genre007",
          name: "Sci-Fi",
          description: "Science fiction exploring futuristic tech and space.",
          isActive: true,
          createdAt: new Date("2023-02-20"),
          updatedAt: new Date("2025-07-01"),
          movies: [],
        },
        {
          id: "genre002",
          name: "Adventure",
          description: "Exciting journeys and explorations across vast lands.",
          isActive: true,
          createdAt: new Date("2023-10-05"),
          updatedAt: new Date("2025-01-15"),
          movies: [],
        },
      ],
      isActive: true,
      createdAt: new Date("2025-06-12T13:00:00Z"),
      updatedAt: new Date("2025-08-10T10:20:00Z"),
    },
    {
      id: "movie005",
      title: "Rhythm & Rise",
      description:
        "A young dancer overcomes adversity to win the biggest street dance championship.",
      duration: 109,
      releaseDate: new Date("2024-07-10"),
      rating: 7.8,
      thumbnail: "https://cdn.example.com/thumbnails/rhythm-rise.jpg",
      thumbnailPublicId: "movies/rhythm-rise-thumbnail",
      trailerUrl: "https://cdn.example.com/trailers/rhythm-rise.mp4",
      trailerPublicId: "trailers/rhythm-rise-trailer",
      genres: [
        {
          id: "genre008",
          name: "Drama",
          description:
            "Emotionally intense stories focused on character development.",
          isActive: true,
          createdAt: new Date("2023-11-11"),
          updatedAt: new Date("2025-04-01"),
          movies: [],
        },
        {
          id: "genre009",
          name: "Music",
          description:
            "Movies that revolve around musical performance and soundtracks.",
          isActive: true,
          createdAt: new Date("2023-04-22"),
          updatedAt: new Date("2024-12-05"),
          movies: [],
        },
      ],
      isActive: true,
      createdAt: new Date("2024-06-01T14:10:00Z"),
      updatedAt: new Date("2024-08-12T16:40:00Z"),
    },
    {
      id: "movie126",
      title: "Sample Movie 26",
      description: "A brief description of Sample Movie 26.",
      duration: 114,
      releaseDate: new Date("2025-05-26"),
      rating: 8.5,
      thumbnail: "https://cdn.example.com/thumbnails/sample-movie-26.jpg",
      thumbnailPublicId: "movies/sample-movie-26-thumbnail",
      trailerUrl: "https://cdn.example.com/trailers/sample-movie-26.mp4",
      trailerPublicId: "trailers/sample-movie-26-trailer",
      genres: [
        {
          id: "genre009",
          name: "Music",
          description: "Focused on musical performance and life.",
          isActive: true,
          createdAt: new Date("2023-01-01"),
          updatedAt: new Date("2025-01-01"),
          movies: [],
        },
      ],
      isActive: true,
      createdAt: new Date("2024-06-01"),
      updatedAt: new Date("2025-09-01"),
    },
    {
      id: "movie127",
      title: "Sample Movie 27",
      description: "A brief description of Sample Movie 27.",
      duration: 118,
      releaseDate: new Date("2025-04-15"),
      rating: 6.2,
      thumbnail: "https://cdn.example.com/thumbnails/sample-movie-27.jpg",
      thumbnailPublicId: "movies/sample-movie-27-thumbnail",
      trailerUrl: "https://cdn.example.com/trailers/sample-movie-27.mp4",
      trailerPublicId: "trailers/sample-movie-27-trailer",
      genres: [
        {
          id: "genre008",
          name: "Drama",
          description: "Emotionally intense character stories.",
          isActive: true,
          createdAt: new Date("2023-01-01"),
          updatedAt: new Date("2025-01-01"),
          movies: [],
        },
      ],
      isActive: true,
      createdAt: new Date("2024-06-01"),
      updatedAt: new Date("2025-09-01"),
    },
    {
      id: "movie128",
      title: "Sample Movie 28",
      description: "A brief description of Sample Movie 28.",
      duration: 127,
      releaseDate: new Date("2025-10-15"),
      rating: 9.2,
      thumbnail: "https://cdn.example.com/thumbnails/sample-movie-28.jpg",
      thumbnailPublicId: "movies/sample-movie-28-thumbnail",
      trailerUrl: "https://cdn.example.com/trailers/sample-movie-28.mp4",
      trailerPublicId: "trailers/sample-movie-28-trailer",
      genres: [
        {
          id: "genre003",
          name: "Horror",
          description: "Movies that scare or disturb.",
          isActive: true,
          createdAt: new Date("2023-01-01"),
          updatedAt: new Date("2025-01-01"),
          movies: [],
        },
        {
          id: "genre004",
          name: "Mystery",
          description: "Films with puzzles and twists.",
          isActive: true,
          createdAt: new Date("2023-01-01"),
          updatedAt: new Date("2025-01-01"),
          movies: [],
        },
      ],
      isActive: true,
      createdAt: new Date("2024-06-01"),
      updatedAt: new Date("2025-09-01"),
    },
    {
      id: "movie129",
      title: "Sample Movie 29",
      description: "A brief description of Sample Movie 29.",
      duration: 101,
      releaseDate: new Date("2024-03-11"),
      rating: 7.7,
      thumbnail: "https://cdn.example.com/thumbnails/sample-movie-29.jpg",
      thumbnailPublicId: "movies/sample-movie-29-thumbnail",
      trailerUrl: "https://cdn.example.com/trailers/sample-movie-29.mp4",
      trailerPublicId: "trailers/sample-movie-29-trailer",
      genres: [
        {
          id: "genre002",
          name: "Adventure",
          description: "Exciting journeys across vast lands.",
          isActive: true,
          createdAt: new Date("2023-01-01"),
          updatedAt: new Date("2025-01-01"),
          movies: [],
        },
        {
          id: "genre006",
          name: "Thriller",
          description: "Intense plots and suspense.",
          isActive: true,
          createdAt: new Date("2023-01-01"),
          updatedAt: new Date("2025-01-01"),
          movies: [],
        },
      ],
      isActive: true,
      createdAt: new Date("2024-06-01"),
      updatedAt: new Date("2025-09-01"),
    },
    {
      id: "movie130",
      title: "Sample Movie 30",
      description: "A brief description of Sample Movie 30.",
      duration: 135,
      releaseDate: new Date("2025-01-05"),
      rating: 8.3,
      thumbnail: "https://cdn.example.com/thumbnails/sample-movie-30.jpg",
      thumbnailPublicId: "movies/sample-movie-30-thumbnail",
      trailerUrl: "https://cdn.example.com/trailers/sample-movie-30.mp4",
      trailerPublicId: "trailers/sample-movie-30-trailer",
      genres: [
        {
          id: "genre001",
          name: "Fantasy",
          description: "Magical worlds and mythical creatures.",
          isActive: true,
          createdAt: new Date("2023-01-01"),
          updatedAt: new Date("2025-01-01"),
          movies: [],
        },
        {
          id: "genre007",
          name: "Sci-Fi",
          description: "Futuristic tech and space.",
          isActive: true,
          createdAt: new Date("2023-01-01"),
          updatedAt: new Date("2025-01-01"),
          movies: [],
        },
      ],
      isActive: true,
      createdAt: new Date("2024-06-01"),
      updatedAt: new Date("2025-09-01"),
    },
    {
      id: "movie131",
      title: "Sample Movie 31",
      description: "A brief description of Sample Movie 31.",
      duration: 99,
      releaseDate: new Date("2024-10-21"),
      rating: 7.0,
      thumbnail: "https://cdn.example.com/thumbnails/sample-movie-31.jpg",
      thumbnailPublicId: "movies/sample-movie-31-thumbnail",
      trailerUrl: "https://cdn.example.com/trailers/sample-movie-31.mp4",
      trailerPublicId: "trailers/sample-movie-31-trailer",
      genres: [
        {
          id: "genre005",
          name: "Action",
          description: "High-octane films with fights and chases.",
          isActive: true,
          createdAt: new Date("2023-01-01"),
          updatedAt: new Date("2025-01-01"),
          movies: [],
        },
      ],
      isActive: true,
      createdAt: new Date("2024-06-01"),
      updatedAt: new Date("2025-09-01"),
    },
    {
      id: "movie132",
      title: "Sample Movie 32",
      description: "A brief description of Sample Movie 32.",
      duration: 121,
      releaseDate: new Date("2025-06-06"),
      rating: 8.7,
      thumbnail: "https://cdn.example.com/thumbnails/sample-movie-32.jpg",
      thumbnailPublicId: "movies/sample-movie-32-thumbnail",
      trailerUrl: "https://cdn.example.com/trailers/sample-movie-32.mp4",
      trailerPublicId: "trailers/sample-movie-32-trailer",
      genres: [
        {
          id: "genre007",
          name: "Sci-Fi",
          description: "Futuristic tech and space.",
          isActive: true,
          createdAt: new Date("2023-01-01"),
          updatedAt: new Date("2025-01-01"),
          movies: [],
        },
      ],
      isActive: true,
      createdAt: new Date("2024-06-01"),
      updatedAt: new Date("2025-09-01"),
    },
    {
      id: "movie133",
      title: "Sample Movie 33",
      description: "A brief description of Sample Movie 33.",
      duration: 112,
      releaseDate: new Date("2024-11-30"),
      rating: 7.3,
      thumbnail: "https://cdn.example.com/thumbnails/sample-movie-33.jpg",
      thumbnailPublicId: "movies/sample-movie-33-thumbnail",
      trailerUrl: "https://cdn.example.com/trailers/sample-movie-33.mp4",
      trailerPublicId: "trailers/sample-movie-33-trailer",
      genres: [
        {
          id: "genre006",
          name: "Thriller",
          description: "Intense plots and suspense.",
          isActive: true,
          createdAt: new Date("2023-01-01"),
          updatedAt: new Date("2025-01-01"),
          movies: [],
        },
        {
          id: "genre004",
          name: "Mystery",
          description: "Films with puzzles and twists.",
          isActive: true,
          createdAt: new Date("2023-01-01"),
          updatedAt: new Date("2025-01-01"),
          movies: [],
        },
      ],
      isActive: true,
      createdAt: new Date("2024-06-01"),
      updatedAt: new Date("2025-09-01"),
    },
    {
      id: "movie134",
      title: "Sample Movie 34",
      description: "A brief description of Sample Movie 34.",
      duration: 105,
      releaseDate: new Date("2025-03-18"),
      rating: 6.9,
      thumbnail: "https://cdn.example.com/thumbnails/sample-movie-34.jpg",
      thumbnailPublicId: "movies/sample-movie-34-thumbnail",
      trailerUrl: "https://cdn.example.com/trailers/sample-movie-34.mp4",
      trailerPublicId: "trailers/sample-movie-34-trailer",
      genres: [
        {
          id: "genre002",
          name: "Adventure",
          description: "Exciting journeys across vast lands.",
          isActive: true,
          createdAt: new Date("2023-01-01"),
          updatedAt: new Date("2025-01-01"),
          movies: [],
        },
      ],
      isActive: true,
      createdAt: new Date("2024-06-01"),
      updatedAt: new Date("2025-09-01"),
    },
    {
      id: "movie135",
      title: "Sample Movie 35",
      description: "A brief description of Sample Movie 35.",
      duration: 130,
      releaseDate: new Date("2024-09-14"),
      rating: 9.0,
      thumbnail: "https://cdn.example.com/thumbnails/sample-movie-35.jpg",
      thumbnailPublicId: "movies/sample-movie-35-thumbnail",
      trailerUrl: "https://cdn.example.com/trailers/sample-movie-35.mp4",
      trailerPublicId: "trailers/sample-movie-35-trailer",
      genres: [
        {
          id: "genre001",
          name: "Fantasy",
          description: "Magical worlds and mythical creatures.",
          isActive: true,
          createdAt: new Date("2023-01-01"),
          updatedAt: new Date("2025-01-01"),
          movies: [],
        },
        {
          id: "genre009",
          name: "Music",
          description: "Focused on musical performance and life.",
          isActive: true,
          createdAt: new Date("2023-01-01"),
          updatedAt: new Date("2025-01-01"),
          movies: [],
        },
      ],
      isActive: true,
      createdAt: new Date("2024-06-01"),
      updatedAt: new Date("2025-09-01"),
    },
  ];
}

export default async function MoviePage() {
  const movies = await getMovies();

  return (
    <div className="container">
      <DataTable columns={columns} data={movies} />
    </div>
  );
}
